name: Actualización semanal del README v2

on:
  schedule:
    - cron: '0 0 * * 0'  # Se ejecuta cada domingo a las 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Debug - Verificar que el token esté presente
        run: |
          if [ -z "$PERSONAL_GITHUB_TOKEN" ]; then 
            echo "Token no encontrado"; 
            exit 1; 
          else 
            echo "Token encontrado"; 
          fi

      - name: Ejecutar script para actualizar estadísticas en el README
        run: python update_stats.py

      - name: Commit y push de cambios
        run: |
          git config --local user.email "alvaro_dangond@hotmail.com"
          git config --local user.name "Alvaro Dangond"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Actualización semanal automatizada de estadísticas en el README [skip ci]"
          git push

