name: Actualización semanal del README

on:
  schedule:
    - cron: '0 0 * * 0'  # Se ejecuta cada domingo a las 00:00 UTC
  workflow_dispatch:     # Permite ejecutar el workflow manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update Profile README
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar script de actualización del README
        uses: Readme-workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
